# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0ea6b60b9ebf756653e33bcc09344e53"
application_url = "https://hotels-confidentiality-liverpool-ice.trycloudflare.com"
embedded = true
name = "wishlist-app"
handle = "wishlist-app-277"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://hotels-confidentiality-liverpool-ice.trycloudflare.com/auth/callback",
  "https://hotels-confidentiality-liverpool-ice.trycloudflare.com/auth/shopify/callback",
  "https://hotels-confidentiality-liverpool-ice.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
include_config_on_deploy = true
dev_store_url = "lovethebug.myshopify.com"
automatically_update_urls_on_dev = true
